### ISSUE TITLE
Criação de conta no Google Play

### ISSUE THREAD

**Issue by tiagoshibata** [CaronaUSP/carona-usp-servidor#6]
- [ ] Precisamos de uma conta se pretendemos publicar o aplicativo

**Comment by tiagoshibata** [comment]
O conta pode ser criada [aqui](https://play.google.com/apps/publish/signup/) com custo único de R$25,00. Precisamos decidir quem será o dono da conta e enviara o apk, @mateusnakajo pode ficar com isso?

**Comment by mateusnakajo** [comment]
Posso. Eu fico com essa parte

Em 17 de maio de 2014 10:55, Tiago Koji Castro Shibata <
notifications@github.com> escreveu:
